name: SRA Board component
on: [push, pull_request]

jobs:
  build-test:
    name: Test Build of component
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v4.1
    steps:  
      - uses: actions/checkout@v2 
        with:
          repository: SRA-VJTI/sra-board-examples
      - uses: actions/checkout@v2
        with:
          path: components/
      - name: Test Bar Graph
        run: |
          . $IDF_PATH/export.sh
          cd bar_graph
          idf.py build
      - name: Test LSA
        run: |
          . $IDF_PATH/export.sh
          cd lsa
          idf.py build
      - name: Test Motor Driver
        run: |
          . $IDF_PATH/export.sh
          cd motor_driver
          idf.py build
      - name: Test MPU6050
        run: |
          . $IDF_PATH/export.sh
          cd mpu6050
          idf.py build
      - name: Test Servos
        run: |
          . $IDF_PATH/export.sh
          cd servos
          idf.py build
      - name: Test Switches
        run: |
          . $IDF_PATH/export.sh
          cd switches
          idf.py build